name: update mainfest on push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run merge
        run: python ./.github/script/merge.py

      - name: Commit files
        run: |
          git config user.email github-actions@github.com
          git config user.name  GitHub-Action
          git add .
          git commit -m "update mainfest" -a
          git push origin master
